SET(P_C_BINDING_SRCS
  c_binding/cb_globals.c
  c_binding/helpers/build_tran_matrix.c
  c_binding/helpers/build_transform.c
  c_binding/helpers/build_transform3.c
  c_binding/helpers/check_event_class.c
  c_binding/helpers/check_loc_data_record.c
  c_binding/helpers/check_pick_data_record.c
  c_binding/helpers/check_stroke_data_record.c
  c_binding/helpers/inp_dispatch_next.c
  c_binding/helpers/inp_event_poll.c
  c_binding/helpers/input_ws_open.c
  c_binding/helpers/inq_filter.c
  c_binding/helpers/pinq_table_indices.c
  c_binding/helpers/request_device.c
  c_binding/helpers/sample_device.c
  c_binding/helpers/set_mode.c
  c_binding/helpers/valid_ar_fname.c
  c_binding/padd_names_set.c
  c_binding/panno_text_rel.c
  c_binding/panno_text_rel3.c
  c_binding/par_all_structs.c
  c_binding/par_struct_nets.c
  c_binding/par_structs.c
  c_binding/pawait_event.c
  c_binding/pbuild_tran_matrix3.c
  c_binding/pchange_struct_id.c
  c_binding/pchange_struct_id_refs.c
  c_binding/pchange_struct_refs.c
  c_binding/pclose_ar_file.c
  c_binding/pclose_phigs.c
  c_binding/pclose_struct.c
  c_binding/pclose_ws.c
  c_binding/pcompose_matrix.c
  c_binding/pcompose_matrix3.c
  c_binding/pcompose_tran_matrix.c
  c_binding/pcompose_tran_matrix3.c
  c_binding/pcopy_all_elems_struct.c
  c_binding/pcreate_store.c
  c_binding/pdel_all_structs.c
  c_binding/pdel_all_structs_ar.c
  c_binding/pdel_elem.c
  c_binding/pdel_elem_range.c
  c_binding/pdel_elems_labels.c
  c_binding/pdel_store.c
  c_binding/pdel_struct.c
  c_binding/pdel_struct_net.c
  c_binding/pdel_struct_nets_ar.c
  c_binding/pdel_structs_ar.c
  c_binding/pelem_search.c
  c_binding/pempty_struct.c
  c_binding/peval_view_map_matrix.c
  c_binding/peval_view_map_matrix3.c
  c_binding/peval_view_ori_matrix.c
  c_binding/peval_view_ori_matrix3.c
  c_binding/pexec_struct.c
  c_binding/pfill_area.c
  c_binding/pfill_area3.c
  c_binding/pfill_area_set.c
  c_binding/pfill_area_set3.c
  c_binding/pfill_area_set3_data.c
  c_binding/pfill_area_set_data.c
  c_binding/pflush_events.c
  c_binding/pget_choice.c
  c_binding/pget_loc.c
  c_binding/pget_loc3.c
  c_binding/pget_pick.c
  c_binding/pget_stroke.c
  c_binding/pget_stroke3.c
  c_binding/pget_val.c
  c_binding/phg_cb_destroy_all_stores.c
  c_binding/phg_cb_resize_store.c
  c_binding/phg_cb_store_el_data.c
  c_binding/phg_cb_store_el_size.c
  c_binding/pinit_choice3.c
  c_binding/pinit_loc3.c
  c_binding/pinit_pick3.c
  c_binding/pinit_string.c
  c_binding/pinit_string3.c
  c_binding/pinit_stroke3.c
  c_binding/pinit_val3.c
  c_binding/pinq_all_conf_structs.c
  c_binding/pinq_ar_files.c
  c_binding/pinq_ar_st.c
  c_binding/pinq_colr_rep.c
  c_binding/pinq_conf_res.c
  c_binding/pinq_conf_structs_net.c
  c_binding/pinq_cur_elem_content.c
  c_binding/pinq_cur_elem_type_size.c
  c_binding/pinq_disp_space_size3.c
  c_binding/pinq_edge_rep.c
  c_binding/pinq_edit_mode.c
  c_binding/pinq_elem_content.c
  c_binding/pinq_elem_ptr.c
  c_binding/pinq_elem_type_size.c
  c_binding/pinq_int_rep.c
  c_binding/pinq_invis_filter.c
  c_binding/pinq_light_src_rep.c
  c_binding/pinq_line_rep.c
  c_binding/pinq_list_colr_inds.c
  c_binding/pinq_list_edge_inds.c
  c_binding/pinq_list_int_inds.c
  c_binding/pinq_list_line_inds.c
  c_binding/pinq_list_marker_inds.c
  c_binding/pinq_list_text_inds.c
  c_binding/pinq_list_view_inds.c
  c_binding/pinq_marker_rep.c
  c_binding/pinq_open_struct.c
  c_binding/pinq_open_wss.c
  c_binding/pinq_struct_st.c
  c_binding/pinq_struct_status.c
  c_binding/pinq_text_rep.c
  c_binding/pinq_ws_cat.c
  c_binding/pinq_ws_conn_type.c
  c_binding/pinq_ws_st.c
  c_binding/plabel.c
  c_binding/pmessage.c
  c_binding/poffset_elem_ptr.c
  c_binding/popen_ar_file.c
  c_binding/popen_phigs.c
  c_binding/popen_struct.c
  c_binding/popen_ws.c
  c_binding/ppolyline.c
  c_binding/ppolyline3.c
  c_binding/ppolymarker.c
  c_binding/ppolymarker3.c
  c_binding/ppost_struct.c
  c_binding/predraw_all_structs.c
  c_binding/premove_names_set.c
  c_binding/preq_choice.c
  c_binding/preq_loc3.c
  c_binding/preq_pick.c
  c_binding/preq_string.c
  c_binding/preq_stroke3.c
  c_binding/preq_valuator.c
  c_binding/pret_all_structs.c
  c_binding/pret_struct_ids.c
  c_binding/pret_struct_nets.c
  c_binding/pret_structs.c
  c_binding/protate.c
  c_binding/protate_x.c
  c_binding/protate_y.c
  c_binding/protate_z.c
  c_binding/psample_loc.c
  c_binding/psample_loc3.c
  c_binding/psample_pick.c
  c_binding/psample_string.c
  c_binding/psample_stroke.c
  c_binding/psample_stroke3.c
  c_binding/pscale.c
  c_binding/pscale3.c
  c_binding/pset_alpha_channel.c
  c_binding/pset_anno_char_ht.c
  c_binding/pset_anno_char_up_vec.c
  c_binding/pset_anno_path.c
  c_binding/pset_back_int_colr.c
  c_binding/pset_back_int_colr_ind.c
  c_binding/pset_back_int_shad_meth.c
  c_binding/pset_back_int_style.c
  c_binding/pset_back_int_style_ind.c
  c_binding/pset_back_refl_eqn.c
  c_binding/pset_back_refl_props.c
  c_binding/pset_char_expan.c
  c_binding/pset_char_ht.c
  c_binding/pset_char_space.c
  c_binding/pset_char_up_vec.c
  c_binding/pset_choice_mode.c
  c_binding/pset_colr_model.c
  c_binding/pset_colr_rep.c
  c_binding/pset_conf_res.c
  c_binding/pset_disp_upd_st.c
  c_binding/pset_edge_colr.c
  c_binding/pset_edge_colr_ind.c
  c_binding/pset_edge_flag.c
  c_binding/pset_edge_ind.c
  c_binding/pset_edge_rep.c
  c_binding/pset_edgetype.c
  c_binding/pset_edgewidth.c
  c_binding/pset_edit_mode.c
  c_binding/pset_elem_ptr.c
  c_binding/pset_elem_ptr_label.c
  c_binding/pset_face_cull_mode.c
  c_binding/pset_face_disting_mode.c
  c_binding/pset_global_tran3.c
  c_binding/pset_highl_filter.c
  c_binding/pset_hlhsr_id.c
  c_binding/pset_hlhsr_mode.c
  c_binding/pset_indiv_asf.c
  c_binding/pset_int_colr.c
  c_binding/pset_int_colr_ind.c
  c_binding/pset_int_ind.c
  c_binding/pset_int_rep.c
  c_binding/pset_int_shad_meth.c
  c_binding/pset_int_style.c
  c_binding/pset_int_style_ind.c
  c_binding/pset_invis_filter.c
  c_binding/pset_light_src_rep.c
  c_binding/pset_light_src_state.c
  c_binding/pset_line_colr.c
  c_binding/pset_line_colr_ind.c
  c_binding/pset_line_ind.c
  c_binding/pset_line_rep.c
  c_binding/pset_linetype.c
  c_binding/pset_linewidth.c
  c_binding/pset_loc_mode.c
  c_binding/pset_local_tran3.c
  c_binding/pset_marker_colr.c
  c_binding/pset_marker_colr_ind.c
  c_binding/pset_marker_ind.c
  c_binding/pset_marker_rep.c
  c_binding/pset_marker_size.c
  c_binding/pset_marker_type.c
  c_binding/pset_model_clip_ind.c
  c_binding/pset_model_clip_vol3.c
  c_binding/pset_of_fill_area_set3_data.c
  c_binding/pset_pick_filter.c
  c_binding/pset_pick_id.c
  c_binding/pset_pick_mode.c
  c_binding/pset_refl_eqn.c
  c_binding/pset_refl_model.c
  c_binding/pset_refl_props.c
  c_binding/pset_string_mode.c
  c_binding/pset_stroke_mode.c
  c_binding/pset_text_align.c
  c_binding/pset_text_colr.c
  c_binding/pset_text_colr_ind.c
  c_binding/pset_text_font.c
  c_binding/pset_text_ind.c
  c_binding/pset_text_path.c
  c_binding/pset_text_prec.c
  c_binding/pset_text_rep.c
  c_binding/pset_val_mode.c
  c_binding/pset_view_ind.c
  c_binding/pset_view_tran_in_pri.c
  c_binding/pset_ws_vp.c
  c_binding/pset_ws_vp3.c
  c_binding/pset_ws_win.c
  c_binding/pset_ws_win3.c
  c_binding/ptext.c
  c_binding/ptext3.c
  c_binding/ptran_point.c
  c_binding/ptran_point3.c
  c_binding/ptranslate.c
  c_binding/ptranslate3.c
  c_binding/punpost_all_structs.c
  c_binding/punpost_struct.c
  c_binding/pupd_ws.c
  c_binding/pxinq_conf_hcsf.c
  c_binding/pxset_conf_file_name.c
  c_binding/pxset_conf_hcsf.c
)

SET(P_F_BINDING_SRCS
  f_binding/dumpstr.c
  f_binding/pads.c
  f_binding/patr.c
  f_binding/patr3.c
  f_binding/pbltm3.c
  f_binding/pbsi.c
  f_binding/pcelst.c
  f_binding/pclph.c
  f_binding/pclst.c
  f_binding/pclwk.c
  f_binding/pdas.c
  f_binding/pdel.c
  f_binding/pdst.c
  f_binding/pels.c
  f_binding/pevmm3.c
  f_binding/pevom3.c
  f_binding/pexst.c
  f_binding/pfa.c
  f_binding/pfas3d.c
  f_binding/pflush.c
  f_binding/pgtch.c
  f_binding/pgtpk.c
  f_binding/pgtvl.c
  f_binding/pinch3.c
  f_binding/pinlc.c
  f_binding/pinlc3.c
  f_binding/pinpk.c
  f_binding/pinst.c
  f_binding/pinst3.c
  f_binding/pinvl3.c
  f_binding/plb.c
  f_binding/pmsg.c
  f_binding/popph.c
  f_binding/popst.c
  f_binding/popwk.c
  f_binding/posep.c
  f_binding/ppl.c
  f_binding/ppl3.c
  f_binding/ppm.c
  f_binding/ppost.c
  f_binding/pprec.c
  f_binding/pqcf.c
  f_binding/pqcr.c
  f_binding/pqdlc3.c
  f_binding/pqdsp3.c
  f_binding/pqeco.c
  f_binding/pqedm.c
  f_binding/pqhrm.c
  f_binding/pqpost.c
  f_binding/pqstrs.c
  f_binding/pqstst.c
  f_binding/pqvwr.c
  f_binding/pqwkpo.c
  f_binding/pqwkt.c
  f_binding/pqwkt3.c
  f_binding/pres.c
  f_binding/prqch.c
  f_binding/prqlc3.c
  f_binding/prqpk.c
  f_binding/prqst.c
  f_binding/prqvl.c
  f_binding/prst.c
  f_binding/psalch.c
  f_binding/psatal.c
  f_binding/psatch.c
  f_binding/psatcu.c
  f_binding/psatp.c
  f_binding/psbic.c
  f_binding/psbici.c
  f_binding/psbis.c
  f_binding/psbisi.c
  f_binding/psbism.c
  f_binding/psbrfm.c
  f_binding/pschh.c
  f_binding/pschm.c
  f_binding/pschsp.c
  f_binding/pschup.c
  f_binding/pschxp.c
  f_binding/pscm.c
  f_binding/pscr.c
  f_binding/psdus.c
  f_binding/psedci.c
  f_binding/psedfg.c
  f_binding/psedi.c
  f_binding/psedm.c
  f_binding/psedr.c
  f_binding/psedt.c
  f_binding/psep.c
  f_binding/pseplb.c
  f_binding/psewsc.c
  f_binding/psfcm.c
  f_binding/psfdm.c
  f_binding/psfname.c
  f_binding/psgmt3.c
  f_binding/pshlft.c
  f_binding/pshrid.c
  f_binding/pshrm.c
  f_binding/psiasf.c
  f_binding/psici.c
  f_binding/psii.c
  f_binding/psir.c
  f_binding/psis.c
  f_binding/psisi.c
  f_binding/psism.c
  f_binding/pslcm.c
  f_binding/pslmt3.c
  f_binding/psln.c
  f_binding/pslsr.c
  f_binding/pslss.c
  f_binding/pslwsc.c
  f_binding/psmcli.c
  f_binding/psmcv3.c
  f_binding/psmk.c
  f_binding/psmksc.c
  f_binding/psmlc.c
  f_binding/psmlc3.c
  f_binding/psmpk.c
  f_binding/psmst.c
  f_binding/pspcli.c
  f_binding/pspkft.c
  f_binding/pspkid.c
  f_binding/pspkm.c
  f_binding/psplr.c
  f_binding/pspmci.c
  f_binding/pspmi.c
  f_binding/pspmr.c
  f_binding/psrfeq.c
  f_binding/psrfm.c
  f_binding/psrfp.c
  f_binding/psstm.c
  f_binding/pstxal.c
  f_binding/pstxci.c
  f_binding/pstxfn.c
  f_binding/pstxi.c
  f_binding/pstxp.c
  f_binding/pstxpr.c
  f_binding/pstxr.c
  f_binding/psvlm.c
  f_binding/psvwi.c
  f_binding/psvwr3.c
  f_binding/pswkv3.c
  f_binding/pswkw.c
  f_binding/pswkw3.c
  f_binding/ptx.c
  f_binding/ptx3.c
  f_binding/pupast.c
  f_binding/pupost.c
  f_binding/puwk.c
  f_binding/pwait.c
  f_binding/pxndef.c
  f_binding/pxqhcsf.c
  f_binding/pxscm.c
  f_binding/pxshcsf.c
  f_binding/pxshlc.c
)
