name: OpenPHIGS build CI on Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64

    steps:
    - uses: actions/checkout@v4

    - name: dependencies
      run: sudo apt install cmake gcc gfortran libx11-dev libglu1-mesa-dev libmotif-dev tcsh libxaw7-dev libglew-dev libdlm-dev

    - name: clean
      run: make clean

    - name: configure
      run: make config

    - name: Build
      run: make build

    - name: Install test
      run: make install
